### ISSUE TITLE
vessel start: fails with "unable to connect to beta"

### ISSUE THREAD

**Issue by mtlynch** [Vessel-App/vessel-cli#25]
`vessel start` fails with this error message:

```bash
 vessel --verbose start
error starting syncing: mutagen sync error: exit status 1 
Connecting to agent (POSIX)...                                                  
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: ssh: connect to host 2a09:8280:1::3:996b port 22: Network is unreachable)
```

I'm not totally sure that `vessel init` succeeded because it never showed a success message:

```bash
$ vessel --verbose init
✔ App Name: █inypilotkvm-com
✔ Other: cimg/node:16.14.2█
✔ cimg/node:16.14.2
✔ Environment ready!
Can we add a Host entry to your ~/.ssh/config file ('N' will output to terminal instead): y
✔ Mutagen is ready
⠏ Waiting for environment to become reachable<nil>
```

But it did successfully create a machine in my Fly.io account.

### Environment

```bash
$ vessel --version
0.0.17

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

$ uname -a
Linux tp 5.11.22-3-pve #1 SMP PVE 5.11.22-6 (Wed, 28 Jul 2021 10:51:12 +0200) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fideloper** [comment]
This means that it cannot connect over SSH to the machine

Based on your output, it looks like step `⠏ Waiting for environment to become reachable<nil>` never finished? That should turn into a check mark when it's able to connect to the machine over SSH.

It's possible for some things to be funky on Fly's end, although I've had issues with this specific step before as well.

Usually it was network related, and trying again helps after deleting the machine, `~/.fly/envs` stuff, and perhaps clearing out entries in `~/.ssh/config`.

The relevant message is the last part of the error that was returned by Mutagen:

```
EOF (error output: ssh: connect to host 2a09:8280:1::3:996b port 22: Network is unreachable)
```

It's possible the IPv6 wasn't working, but it might be worth checking to ensure the Machine was launched/working (perhaps in your Fly dashboard's Log area, or `fly logs -a <app-name>`)

**Comment by mtlynch** [comment]
I tried checking fly logs, and I see:

```bash
$ fly logs -a tinypilotkvm-com
2022-11-11T23:11:19Z runner[d568350c72978e] ewr [info]Reserved resources for machine 'd568350c72978e'
2022-11-11T23:11:19Z runner[d568350c72978e] ewr [info]Pulling container image
2022-11-11T23:11:20Z runner[d568350c72978e] ewr [info]Unpacking image
2022-11-11T23:11:30Z runner[d568350c72978e] ewr [info]Configuring firecracker
2022-11-11T23:11:33Z runner[d568350c72978e] ewr [info]machine exited with exit code 0, not restarting
```

Nothing really jumps out to me. I'll try adding some debug logging to the binary to see if I can find anything.

**Comment by mtlynch** [comment]
After applying #28, I can see the error now:

```bash
$ vessel -v init
✔ App Name: █inypilotkvm-com
✔ vesselapp/php:8.1
✔ Environment ready!
Can we add a Host entry to your ~/.ssh/config file ('N' will output to terminal instead): y
✔ Mutagen is ready
⠏ Waiting for environment to become reachablecannot connect [2a09:8280:1::3:9a97]:22: dial tcp [2a09:8280:1::3:9a97]:22: connect: network is unreachable
```

**Comment by fideloper** [comment]
I'm guessing the Docker image is NOT extending the base image created for this project.

The base image has SSH installed and listening on port 2222 for connections. There's also a Rust program that handles...other stuff (it's not a requirement but it will handle shutting down the VM when there's no SSH connections active)

That's mentioned here: https://github.com/Vessel-App/vessel-cli#custom-dev-environments

And more details are in this article, roughly around this part of it: https://fly.io/laravel-bytes/deus-ex-machina/#what-s-running

**Comment by mtlynch** [comment]
I'm testing this with `vesselapp/php:8.1`:


```bash
$ vessel -v init
✔ App Name: █inypilotkvm-com
✔ vesselapp/php:8.1
✔ Environment ready!
Can we add a Host entry to your ~/.ssh/config file ('N' will output to terminal instead): y
✔ Mutagen is ready
⠏ Waiting for environment to become reachablecannot connect [2a09:8280:1::3:9a97]:22: dial tcp [2a09:8280:1::3:9a97]:22: connect: network is unreachable
```

**Comment by fideloper** [comment]
Gotcha - Any chance your ISP doesn't support ipv6?

The `init` command has a `v4` flag that will assign an ipv4 address instead of ipv6

The log output (assuming the above log output for `fly logs -a tinypilotkvm-com` is using the Vessel image) shouldn't `exit 0` that quickly in theory, but instead of should wait a few minute and have some output counting the number of seconds it's idle (with no SSH connection).

**Comment by mtlynch** [comment]
>Any chance your ISP doesn't support ipv6?

Ah, that was it! I got a little farther and then hit a segfault. I applied #29 and I'm still seeing this failure:

```bash
$ vessel -v init -4
App Name: tinypilotkvm-com
█inypilotkvm-com
✔ vesselapp/php:8.1
could not allocate ip: request error: Post "https://api.fly.io/graphql": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
